"""
Authentication Service.

Manages anonymous device identities, token hashing, and authentication verification.
Uses SHA-256 for storing token hashes (raw tokens are never stored in database).
"""
from __future__ import annotations

import hashlib
import secrets
import uuid
from typing import Optional

from app.database import repository as repo
from app.database.models import User


def hash_token(raw_token: str) -> str:
    """Compute SHA-256 hash of a raw token string."""
    return hashlib.sha256(raw_token.encode("utf-8")).hexdigest()


async def register_device(db_path: str, client_token: Optional[str] = None) -> tuple[User, str]:
    """
    Register a new anonymous device / user.

    If client_token is provided (e.g. generated by extension), use it.
    Otherwise generate a cryptographically random token.

    Returns:
        tuple[User, raw_token]
    """
    raw_token = client_token.strip() if client_token else secrets.token_urlsafe(32)
    token_h = hash_token(raw_token)

    # Check if this token is already registered
    existing = await repo.get_user_by_token_hash(db_path, token_h)
    if existing:
        return existing, raw_token

    public_id = f"usr_{uuid.uuid4().hex}"
    user = await repo.create_user(db_path, public_id=public_id, auth_token_hash=token_h)
    return user, raw_token


async def authenticate_token(db_path: str, raw_token: str) -> Optional[User]:
    """
    Authenticate a request using raw Bearer token.
    Returns User if valid, None if invalid.
    """
    if not raw_token or not raw_token.strip():
        return None
    token_h = hash_token(raw_token.strip())
    return await repo.get_user_by_token_hash(db_path, token_h)
